#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

dashboard:
  path: /dashboard
  controller:  App\Controller\DashboardController::index

new:
  path: /register
  controller: App\Controller\SecurityController::new